name: CI

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install wheel
        run: pip install wheel
      - name: Build wheel
        run: pip wheel ansible==${{github.ref_name}}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ansible-*-py3-none-any.whl
            ansible_core-*-py3-none-any.whl
